{% set name = "barnaba" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/srnas/barnaba/archive/{{ version }}.tar.gz
  sha256: cdf243f7e13d5266a4397641d3609409c4b2d7b7765a18bc98a66e1e25f29258

build:
  # Uncomment the following line if the package is pure Python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python for more details.
  noarch: python
  number: 0
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - setuptools_scm
    - setuptools_scm_git_archive
  host:
    - python
    - pip
  run:
    - future
    - mdtraj
    - numpy
    - python
    - scikit-learn

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - barnaba
  commands:
    - barnaba -h

about:
  home: https://github.com/srnas/barnaba
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Barnaba is a tool for analyzing RNA three-dimensional structures and simulations'

  # The remaining entries in this section are optional, but recommended.
  description: |
    Barnaba is a tool for analyzing RNA three-dimensional structures and simulations.
    Barnaba uses MDtraj to read/write topology and trajectory files, as such it supports
    several formats including pdb, xtc, trr, dcd, binpos, netcdf, mdcrd, prmtop, and more.
    Barnaba has been developed by Sandro Bottaro with the crucial help of Giovanni Bussi, Giovanni Pinamonti,
    Sabine Rei{\ss}er and Wouter Boomsma.
  dev_url: https://github.com/srnas/barnaba

extra:
  recipe-maintainers:
    - GiovanniBussi
