package:
  name: gromacs
  version: 2018.6

source:
  url: http://ftp.gromacs.org/pub/gromacs/gromacs-2018.6.tar.gz
  md5: 997f2b8108197780d61b23b5eb05644a

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - binutils
    - cmake
    - plumed =2.5.1
    - python
  host:
    - fftw
  run:
    - fftw
    - plumed >=2

test:
  commands:
    - gmx -version
    - gmx mdrun -h | grep plumed

about:
  home: http://www.gromacs.org/
  license: LGPL-2.1
  license_family: GPL
  license_file: COPYING
  summary: 'GROMACS is a versatile package to perform molecular dynamics.'
  description: |
    GROMACS is a versatile package to perform molecular dynamics.
    This build is modified in order to take advantage of methods implemented
    in the PLUMED library.

extra:
  recipe-maintainers:
    - GiovanniBussi
